#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_soul = env_modules.Clone()

module_obj = []

env_soul.add_source_files(module_obj, "*.cpp")

env.modules_sources += module_obj

# Unit tests live in tests/*.h and are discovered by modules/SCsub when env["tests"] is set;
# nothing extra to compile here.
