#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_opendust_os = env_modules.Clone()

env_opendust_os.add_source_files(env.modules_sources, "*.cpp")
